version: '3.8'
services:
  db:
    image: postgres:15-alpine
    container_name: kuran_postgres
    restart: always
    environment:
      POSTGRES_USER: kuran_admin
      POSTGRES_PASSWORD: secure_password_123
      POSTGRES_DB: kuran_db
    ports:
      - "5455:5432"
    volumes:
      - kuran_pgdata:/var/lib/postgresql/data

volumes:
  kuran_pgdata:
