"use client";

import Link from "next/link";
import { useSearchParams } from "next/navigation";

type Language = "tr" | "en" | "ar" | "de" | "fr" | "es";
type Kind = "privacy" | "terms" | "support" | "deletion";

const labels: Record<Language, { home: string; login: string; profile: string; aiReport: string; retentionTitle: string; retention: string }> = {
  tr: { home: "Ana sayfa", login: "Giriş", profile: "Profil", aiReport: "Bildirilen bir AI yanıtının inceleme kaydında yanıtın en fazla 500 karakterlik bölümü de bulunabilir.", retentionTitle: "Saklama süreleri", retention: "Ürün analitiği en fazla 13 ay, bildirilen AI yanıtı kayıtları en fazla 180 gün tutulur. Hesaba bağlı veriler hesap silme süreci sonunda silinir; yasal zorunluluklar daha uzun saklama gerektirebilir." },
  en: { home: "Home", login: "Sign in", profile: "Profile", aiReport: "A reported AI response may also retain an excerpt of up to 500 characters for review.", retentionTitle: "Retention", retention: "Product analytics is retained for up to 13 months and reported AI response records for up to 180 days. Account-linked data is removed after account deletion, unless a longer period is legally required." },
  de: { home: "Startseite", login: "Anmelden", profile: "Profil", aiReport: "Bei einer gemeldeten AI-Antwort kann außerdem ein Ausschnitt von höchstens 500 Zeichen zur Prüfung gespeichert werden.", retentionTitle: "Speicherdauer", retention: "Produktanalysen werden bis zu 13 Monate und gemeldete AI-Antworten bis zu 180 Tage gespeichert. Kontobezogene Daten werden nach der Kontolöschung entfernt, sofern keine längere gesetzliche Pflicht besteht." },
  fr: { home: "Accueil", login: "Connexion", profile: "Profil", aiReport: "Une réponse IA signalée peut aussi conserver un extrait de 500 caractères maximum pour examen.", retentionTitle: "Conservation", retention: "Les données d’analyse sont conservées jusqu’à 13 mois et les réponses IA signalées jusqu’à 180 jours. Les données liées au compte sont supprimées après la suppression du compte, sauf obligation légale contraire." },
  es: { home: "Inicio", login: "Acceder", profile: "Perfil", aiReport: "Una respuesta de IA reportada también puede conservar un fragmento de hasta 500 caracteres para su revisión.", retentionTitle: "Conservación", retention: "Los datos analíticos se conservan hasta 13 meses y las respuestas de IA reportadas hasta 180 días. Los datos vinculados a la cuenta se eliminan tras borrar la cuenta, salvo obligación legal." },
  ar: { home: "الرئيسية", login: "تسجيل الدخول", profile: "الملف الشخصي", aiReport: "قد يحتفظ بلاغ إجابة الذكاء الاصطناعي أيضًا بمقتطف لا يتجاوز 500 حرف للمراجعة.", retentionTitle: "مدة الاحتفاظ", retention: "تُحفظ تحليلات المنتج لمدة تصل إلى 13 شهرًا وسجلات إجابات الذكاء الاصطناعي المبلغ عنها لمدة تصل إلى 180 يومًا. تُحذف البيانات المرتبطة بالحساب بعد حذف الحساب ما لم يفرض القانون مدة أطول." },
};

const copy: Record<Language, Record<Kind, { title: string; intro: string; sections: { title: string; body: string }[] }>> = {
  tr: {
    privacy: { title: "Gizlilik Politikası", intro: "Son güncelleme: 10 Ağustos 2026. Kur’an-ı Kerim Diyor, mahremiyetinizi okuma deneyiminin temel bir parçası kabul eder.", sections: [
      { title: "Topladığımız veriler", body: "İsteğe bağlı hesap için e-posta ve ad; favoriler, koleksiyonlar, yorumlar ve okuma ilerlemesi; bildirim tercihi ve cihaz bildirim anahtarı; rastgele kurulum kimliğiyle uygulama açılışı, ekran/funnel adımı ve anonim ilerleme oranı toplanabilir. Reklam kimliği, kesin konum veya AI sohbet metni analitik amacıyla toplanmaz." },
      { title: "AI sohbeti", body: "Sorunuz, seçilen ayet ve yakın bağlamı yanıt üretmek üzere Google Gemini hizmetine gönderilir. Sohbet geçmişini kendi veritabanımızda saklamayız. Bir AI yanıtını bildirdiğinizde inceleme için yanıt kimliği, ayet referansı, bildirim nedeni, yanıtın en fazla 500 karakterlik bölümü ve isteğe bağlı hesap kimliği saklanır." },
      { title: "Amaç ve paylaşım", body: "Veriler hesap, senkronizasyon, topluluk moderasyonu, bildirim, güvenlik ve ürün iyileştirme için kullanılır. Verileri satmayız ve reklam profili oluşturmayız. Hizmet sağlayıcılar yalnızca işlevi sunmak için gerekli veriye erişebilir." },
      { title: "Kontrol ve silme", body: "Anonim analitiği Ayarlar’dan kapatabilirsiniz. Hesabınızı uygulama içinden veya hesap silme sayfasından silebilirsiniz. Silme talebi 14 gün geri alınabilir durumda tutulur, ardından yasal olarak saklanması gerekmeyen hesap verileri silinir." },
    ]},
    terms: { title: "Kullanım Koşulları", intro: "Uygulamayı kullanarak bu koşulları kabul etmiş olursunuz.", sections: [
      { title: "Dini içerik", body: "Mealler, açıklamalar ve AI yanıtları eğitim ve tefekkür içindir; fetva veya uzman görüşü değildir. Önemli dini kararlar için güvenilir kaynaklara ve ehil kişilere başvurun." },
      { title: "Topluluk", body: "Hakaret, nefret söylemi, taciz, spam, yanıltıcı dini alıntı ve hukuka aykırı içerik yasaktır. İçerikler otomatik ve insan moderasyonuna tabi olabilir; kullanıcılar içerik bildirebilir ve ihlal eden hesaplar sınırlandırılabilir." },
      { title: "Sorumluluk", body: "Hizmeti güvenli ve doğru tutmak için çalışırız ancak kesintisiz veya hatasız olacağını garanti edemeyiz. Hatalı ayet, meal veya AI yanıtlarını destek sayfasından bildirmenizi isteriz." },
    ]},
    support: { title: "Destek", intro: "Teknik sorun, içerik düzeltmesi, gizlilik veya güvenlik bildirimi için destek formunu kullanın.", sections: [{ title: "İletişim", body: "Destek sayfasında konu seçip cihaz türünü, uygulama sürümünü ve sorunun görüldüğü ekranı ekleyin; şifrenizi veya hassas kişisel bilgilerinizi göndermeyin." }, { title: "Yanıt süresi", body: "Güvenlik ve gizlilik bildirimlerini önceliklendirir, diğer taleplere mümkün olan en kısa sürede yanıt veririz." }]},
    deletion: { title: "Hesap ve Veri Silme", intro: "Hesabınızı ve ilişkili verilerinizi uygulama içinden başlatabilirsiniz.", sections: [{ title: "Nasıl silinir?", body: "Uygulama veya web profilinizde Hesabı Sil seçeneğini kullanın. Talep sonrası hesap 14 gün dondurulur; bu sürede giriş yapmak talebi iptal eder. Süre sonunda favoriler, koleksiyonlar, yorumlar, ilerleme ve kullanıcıya bağlı analitik kayıtlar silinir." }, { title: "Hesaba erişemiyorsanız", body: "Destek sayfasında Hesap silme konusunu seçip kayıtlı adresinizi ve talebinizi iletin. Hesabın size ait olduğunu doğrulamamız gerekebilir." }]},
  },
  en: {
    privacy: { title: "Privacy Policy", intro: "Last updated: August 10, 2026. Quran Says treats privacy as a core part of the reading experience.", sections: [{ title: "Data we collect", body: "Optional account email and name; favorites, collections, comments and reading progress; notification preference and push token; app opens, funnel steps and anonymous progress using a random install identifier. We do not collect advertising IDs, precise location or AI chat text for analytics." }, { title: "AI chat", body: "Your question, selected verse and nearby context are sent to Google Gemini to create a response. We do not store chat history in our database. If you report a response, we retain its ID, verse reference, reason, an excerpt of up to 500 characters and optional account ID for review." }, { title: "Use and sharing", body: "Data supports accounts, sync, moderation, notifications, security and product improvement. We do not sell data or build advertising profiles. Providers receive only data required to deliver their service." }, { title: "Control and deletion", body: "Disable anonymous analytics in Settings. Delete your account in the app or through the deletion page. Requests remain reversible for 14 days, then data not legally required is deleted." }]},
    terms: { title: "Terms of Use", intro: "By using the app you agree to these terms.", sections: [{ title: "Religious content", body: "Translations, explanations and AI responses are for education and reflection, not fatwas or professional advice. Consult reliable sources and qualified scholars for important religious decisions." }, { title: "Community", body: "Abuse, hate, harassment, spam, misleading religious quotations and illegal content are prohibited. Content may be automatically and manually moderated; users can report content and violating accounts may be restricted." }, { title: "Responsibility", body: "We work to keep the service accurate and safe but cannot guarantee uninterrupted or error-free operation. Please report Quran text, translation or AI response issues." }]},
    support: { title: "Support", intro: "Use the support form for technical issues, content corrections, privacy or security.", sections: [{ title: "Contact", body: "Select a topic and include device type, app version and affected screen; never send passwords or sensitive personal data." }, { title: "Response", body: "Security and privacy reports are prioritized. We answer other requests as soon as reasonably possible." }]},
    deletion: { title: "Account and Data Deletion", intro: "You can initiate deletion of your account and associated data from inside the app.", sections: [{ title: "How to delete", body: "Choose Delete Account in your app or web profile. The account is frozen for 14 days; signing in cancels the request. Afterwards favorites, collections, comments, progress and user-linked analytics are deleted." }, { title: "No account access", body: "Open the Support page, select Account deletion and include your registered address. We may need to verify ownership." }]},
  },
  de: { privacy: { title: "Datenschutzerklärung", intro: "Stand: 10. August 2026. Datenschutz ist ein wesentlicher Teil der Leseerfahrung.", sections: [{ title: "Daten", body: "Optional: E-Mail und Name; Favoriten, Sammlungen, Kommentare, Lesefortschritt, Benachrichtigungs-Token sowie anonyme Nutzung mit zufälliger Installations-ID. Keine Werbe-ID, kein genauer Standort und keine AI-Chattexte für Analysen." }, { title: "AI-Chat", body: "Frage, Vers und naher Kontext werden zur Antworterstellung an Google Gemini gesendet. Chatverläufe speichern wir nicht. Meldungen enthalten nur Antwort-ID, Vers, Grund und optionale Konto-ID." }, { title: "Nutzung", body: "Daten dienen Konto, Synchronisierung, Moderation, Benachrichtigung, Sicherheit und Verbesserung. Wir verkaufen keine Daten und erstellen keine Werbeprofile." }, { title: "Kontrolle", body: "Analysen können in den Einstellungen deaktiviert werden. Kontolöschung ist in App und Web möglich; nach 14 Tagen werden nicht gesetzlich erforderliche Daten gelöscht." }]}, terms: { title: "Nutzungsbedingungen", intro: "Mit der Nutzung stimmen Sie diesen Bedingungen zu.", sections: [{ title: "Religiöse Inhalte", body: "Übersetzungen und AI-Antworten dienen Bildung und Reflexion, nicht als Fatwa. Wenden Sie sich für wichtige Fragen an verlässliche Quellen und qualifizierte Gelehrte." }, { title: "Community", body: "Hass, Belästigung, Spam, irreführende religiöse Zitate und rechtswidrige Inhalte sind verboten und können moderiert oder gemeldet werden." }]}, support: { title: "Support", intro: "Hilfe bei Technik, Inhalt, Datenschutz oder Sicherheit.", sections: [{ title: "Kontakt", body: "Nutzen Sie das Supportformular und nennen Sie Gerät, App-Version und betroffenen Bildschirm; niemals Passwörter senden." }]}, deletion: { title: "Konto- und Datenlöschung", intro: "Die Löschung kann in der App gestartet werden.", sections: [{ title: "Ablauf", body: "Im Profil Konto löschen wählen. Das Konto wird 14 Tage eingefroren; eine Anmeldung storniert die Löschung. Danach werden zugehörige Daten gelöscht." }, { title: "Kein Zugriff", body: "Wählen Sie auf der Supportseite Kontolöschung und geben Sie Ihre registrierte Adresse an." }] } },
  fr: { privacy: { title: "Politique de confidentialité", intro: "Mise à jour : 10 août 2026. La confidentialité fait partie intégrante de l’expérience.", sections: [{ title: "Données", body: "Facultatif : e-mail et nom ; favoris, collections, commentaires, progression, jeton de notification et usage anonyme via un identifiant aléatoire. Aucun identifiant publicitaire, emplacement précis ou texte de chat IA n’est collecté pour l’analyse." }, { title: "Chat IA", body: "La question, le verset et son contexte proche sont envoyés à Google Gemini. Nous ne conservons pas l’historique. Un signalement contient uniquement l’ID de réponse, le verset, le motif et éventuellement l’ID du compte." }, { title: "Utilisation", body: "Les données servent au compte, à la synchronisation, la modération, la sécurité et l’amélioration. Nous ne vendons pas les données et ne créons pas de profil publicitaire." }, { title: "Contrôle", body: "Désactivez l’analyse dans les réglages. La suppression est disponible dans l’app et sur le web ; après 14 jours, les données non légalement requises sont supprimées." }]}, terms: { title: "Conditions d’utilisation", intro: "En utilisant l’application, vous acceptez ces conditions.", sections: [{ title: "Contenu religieux", body: "Les traductions et réponses IA servent à apprendre et réfléchir ; elles ne constituent pas une fatwa. Consultez des sources fiables et des personnes qualifiées." }, { title: "Communauté", body: "Haine, harcèlement, spam, citations religieuses trompeuses et contenus illégaux sont interdits et peuvent être modérés ou signalés." }]}, support: { title: "Assistance", intro: "Aide technique, contenu, confidentialité ou sécurité.", sections: [{ title: "Contact", body: "Utilisez le formulaire d’assistance et indiquez l’appareil, la version et l’écran concerné ; n’envoyez jamais de mot de passe." }]}, deletion: { title: "Suppression du compte", intro: "La suppression peut être initiée dans l’application.", sections: [{ title: "Procédure", body: "Choisissez Supprimer le compte dans le profil. Le compte est gelé 14 jours ; une connexion annule la demande. Les données associées sont ensuite supprimées." }, { title: "Sans accès", body: "Choisissez Suppression du compte sur la page d’assistance et indiquez votre adresse enregistrée." }] } },
  es: { privacy: { title: "Política de privacidad", intro: "Actualización: 10 de agosto de 2026. La privacidad es parte esencial de la experiencia.", sections: [{ title: "Datos", body: "Opcional: correo y nombre; favoritos, colecciones, comentarios, progreso, token de notificación y uso anónimo mediante un identificador aleatorio. No recopilamos ID publicitario, ubicación precisa ni texto del chat IA para análisis." }, { title: "Chat con IA", body: "La pregunta, la aleya y su contexto cercano se envían a Google Gemini. No almacenamos el historial. Un reporte conserva solo ID de respuesta, aleya, motivo e ID de cuenta opcional." }, { title: "Uso", body: "Los datos sirven para cuentas, sincronización, moderación, seguridad y mejora. No vendemos datos ni creamos perfiles publicitarios." }, { title: "Control", body: "Desactiva el análisis en Ajustes. Puedes borrar la cuenta en la app o web; tras 14 días se eliminan los datos no exigidos legalmente." }]}, terms: { title: "Condiciones de uso", intro: "Al usar la aplicación aceptas estas condiciones.", sections: [{ title: "Contenido religioso", body: "Las traducciones y respuestas de IA son educativas y reflexivas; no son fetuas. Consulta fuentes fiables y personas cualificadas." }, { title: "Comunidad", body: "Se prohíben odio, acoso, spam, citas religiosas engañosas y contenido ilegal; pueden moderarse o denunciarse." }]}, support: { title: "Soporte", intro: "Ayuda técnica, de contenido, privacidad o seguridad.", sections: [{ title: "Contacto", body: "Usa el formulario de soporte e incluye dispositivo, versión y pantalla; nunca envíes contraseñas." }]}, deletion: { title: "Eliminación de cuenta", intro: "Puedes iniciar la eliminación dentro de la aplicación.", sections: [{ title: "Proceso", body: "Elige Eliminar cuenta en el perfil. La cuenta queda congelada 14 días; iniciar sesión cancela la solicitud. Después se borran los datos asociados." }, { title: "Sin acceso", body: "Selecciona Eliminar cuenta en la página de soporte e indica tu dirección registrada." }] } },
  ar: { privacy: { title: "سياسة الخصوصية", intro: "آخر تحديث: 10 أغسطس 2026. الخصوصية جزء أساسي من تجربة القراءة.", sections: [{ title: "البيانات", body: "اختياريًا: البريد والاسم، المفضلة والمجموعات والتعليقات وتقدم القراءة ورمز الإشعارات، واستخدام مجهول بمعرّف تثبيت عشوائي. لا نجمع معرّف الإعلانات أو الموقع الدقيق أو نص محادثة الذكاء الاصطناعي للتحليلات." }, { title: "محادثة الذكاء الاصطناعي", body: "يُرسل السؤال والآية وسياقها القريب إلى Google Gemini لإنشاء الإجابة. لا نخزن سجل المحادثة. يحتفظ البلاغ بمعرّف الإجابة والآية والسبب ومعرّف الحساب الاختياري فقط." }, { title: "الاستخدام", body: "تُستخدم البيانات للحساب والمزامنة والإشراف والأمان والتحسين. لا نبيع البيانات ولا ننشئ ملفات إعلانية." }, { title: "التحكم", body: "يمكن إيقاف التحليلات من الإعدادات. يمكن حذف الحساب من التطبيق أو الويب؛ وبعد 14 يومًا تُحذف البيانات غير المطلوبة قانونيًا." }]}, terms: { title: "شروط الاستخدام", intro: "باستخدام التطبيق فإنك توافق على هذه الشروط.", sections: [{ title: "المحتوى الديني", body: "الترجمات وإجابات الذكاء الاصطناعي للتعلم والتدبر وليست فتوى. ارجع إلى المصادر الموثوقة وأهل العلم في المسائل المهمة." }, { title: "المجتمع", body: "يُحظر خطاب الكراهية والمضايقة والرسائل المزعجة والاقتباسات الدينية المضللة والمحتوى غير القانوني، ويمكن الإبلاغ عنها وإدارتها." }]}, support: { title: "الدعم", intro: "للمساعدة التقنية أو تصحيح المحتوى أو الخصوصية والأمان.", sections: [{ title: "التواصل", body: "استخدم نموذج الدعم واذكر نوع الجهاز وإصدار التطبيق والشاشة، ولا ترسل كلمة المرور." }]}, deletion: { title: "حذف الحساب والبيانات", intro: "يمكن بدء حذف الحساب من داخل التطبيق.", sections: [{ title: "الطريقة", body: "اختر حذف الحساب في الملف الشخصي. يُجمّد الحساب 14 يومًا ويلغي تسجيل الدخول الطلب، ثم تُحذف البيانات المرتبطة." }, { title: "تعذر الوصول", body: "اختر حذف الحساب في صفحة الدعم وأدخل عنوانك المسجل." }] } },
};

export function LegalDocument({ kind }: { kind: Kind }) {
  const params = useSearchParams();
  const requested = params.get("lang") as Language | null;
  const lang: Language = requested && requested in copy ? requested : "tr";
  const document = copy[lang][kind];
  return <main dir={lang === "ar" ? "rtl" : "ltr"} className="mx-auto min-h-screen max-w-3xl px-5 py-12 text-text">
    <Link href="/" className="text-sm font-semibold text-primary">← {labels[lang].home}</Link>
    <h1 className="mt-8 text-3xl font-bold">{document.title}</h1><p className="mt-3 leading-7 text-secondary">{document.intro}</p>
    <div className="mt-8 space-y-7">{document.sections.map((section, index) => <section key={section.title}><h2 className="text-lg font-bold">{section.title}</h2><p className="mt-2 leading-7 text-secondary">{section.body}{kind === "privacy" && index === 1 && lang !== "tr" && lang !== "en" ? ` ${labels[lang].aiReport}` : ""}</p></section>)}</div>
    {kind === "privacy" && <section className="mt-7"><h2 className="text-lg font-bold">{labels[lang].retentionTitle}</h2><p className="mt-2 leading-7 text-secondary">{labels[lang].retention}</p></section>}
    {kind === "deletion" && <div className="mt-8 flex gap-3"><Link href="/login" className="rounded-md bg-primary px-4 py-2 font-semibold text-white">{labels[lang].login}</Link><Link href="/profile" className="rounded-md border border-border px-4 py-2 font-semibold">{labels[lang].profile}</Link></div>}
    {kind === "deletion" && <Link href={`/support?lang=${lang}`} className="mt-4 inline-block text-sm font-semibold text-primary underline">Support</Link>}
    <div className="mt-10 flex flex-wrap gap-2">{(["tr", "en", "ar", "de", "fr", "es"] as Language[]).map((value) => <Link key={value} href={`/${kind === "deletion" ? "account-deletion" : kind}?lang=${value}`} className={`rounded border px-2 py-1 text-xs ${lang === value ? "border-primary text-primary" : "border-border text-muted"}`}>{value.toUpperCase()}</Link>)}</div>
  </main>;
}
