"use client";

import { FormEvent, useEffect, useState } from "react";
import Link from "next/link";
import { useSearchParams } from "next/navigation";
import apiClient from "@/services/apiClient";

type Language = "tr" | "en" | "ar" | "de" | "fr" | "es";
type Copy = { home: string; title: string; intro: string; email: string; emailHint: string; category: string; message: string; placeholder: string; send: string; sending: string; success: string; ticket: string; status: string; check: string; note: string; categories: Record<string, string> };
const categories = ["TECHNICAL", "CONTENT_CORRECTION", "PRIVACY", "ACCOUNT_DELETION", "SECURITY", "OTHER"];
const copy: Record<Language, Copy> = {
  tr: { home: "Ana sayfa", title: "Destek", intro: "Teknik sorun, içerik düzeltmesi, gizlilik, güvenlik veya hesap silme talebinizi doğrudan ekibimize iletin.", email: "E-posta (isteğe bağlı)", emailHint: "Yanıt gerekirse size ulaşabilmemiz için ekleyebilirsiniz.", category: "Konu", message: "Açıklama", placeholder: "Cihaz türünü, uygulama sürümünü ve sorunu açıklayın. Şifre veya hassas bilgi yazmayın.", send: "Talebi gönder", sending: "Gönderiliyor…", success: "Talebiniz alındı. Bilet bilgisi bu cihazda saklandı.", ticket: "Bilet", status: "Durum", check: "Durumu yenile", note: "Destek notu", categories: { TECHNICAL: "Teknik sorun", CONTENT_CORRECTION: "Ayet/meal düzeltmesi", PRIVACY: "Gizlilik", ACCOUNT_DELETION: "Hesap silme", SECURITY: "Güvenlik", OTHER: "Diğer" } },
  en: { home: "Home", title: "Support", intro: "Send technical, content correction, privacy, security or account deletion requests directly to our team.", email: "Email (optional)", emailHint: "Add it if you want us to be able to contact you.", category: "Topic", message: "Details", placeholder: "Include device type, app version and the issue. Do not enter passwords or sensitive data.", send: "Submit request", sending: "Submitting…", success: "Your request was received. Ticket access is stored on this device.", ticket: "Ticket", status: "Status", check: "Refresh status", note: "Support note", categories: { TECHNICAL: "Technical issue", CONTENT_CORRECTION: "Quran/translation correction", PRIVACY: "Privacy", ACCOUNT_DELETION: "Account deletion", SECURITY: "Security", OTHER: "Other" } },
  de: { home: "Startseite", title: "Support", intro: "Sende technische, inhaltliche, Datenschutz-, Sicherheits- oder Löschanfragen direkt an unser Team.", email: "E-Mail (optional)", emailHint: "Angeben, wenn wir dich kontaktieren dürfen.", category: "Thema", message: "Beschreibung", placeholder: "Gerät, App-Version und Problem nennen. Keine Passwörter oder sensiblen Daten eingeben.", send: "Anfrage senden", sending: "Wird gesendet…", success: "Deine Anfrage wurde empfangen. Der Ticketzugang ist auf diesem Gerät gespeichert.", ticket: "Ticket", status: "Status", check: "Status aktualisieren", note: "Support-Notiz", categories: { TECHNICAL: "Technisches Problem", CONTENT_CORRECTION: "Koran-/Übersetzungskorrektur", PRIVACY: "Datenschutz", ACCOUNT_DELETION: "Kontolöschung", SECURITY: "Sicherheit", OTHER: "Sonstiges" } },
  fr: { home: "Accueil", title: "Assistance", intro: "Envoyez directement à notre équipe vos demandes techniques, de correction, confidentialité, sécurité ou suppression.", email: "E-mail (facultatif)", emailHint: "Ajoutez-le si vous souhaitez être contacté.", category: "Sujet", message: "Description", placeholder: "Indiquez l’appareil, la version et le problème. Ne saisissez aucun mot de passe ni donnée sensible.", send: "Envoyer", sending: "Envoi…", success: "Votre demande a été reçue. L’accès au ticket est conservé sur cet appareil.", ticket: "Ticket", status: "Statut", check: "Actualiser", note: "Note de l’assistance", categories: { TECHNICAL: "Problème technique", CONTENT_CORRECTION: "Correction Coran/traduction", PRIVACY: "Confidentialité", ACCOUNT_DELETION: "Suppression du compte", SECURITY: "Sécurité", OTHER: "Autre" } },
  es: { home: "Inicio", title: "Soporte", intro: "Envía directamente al equipo solicitudes técnicas, correcciones, privacidad, seguridad o eliminación de cuenta.", email: "Correo (opcional)", emailHint: "Añádelo si quieres que podamos contactarte.", category: "Tema", message: "Descripción", placeholder: "Indica dispositivo, versión y problema. No escribas contraseñas ni datos sensibles.", send: "Enviar solicitud", sending: "Enviando…", success: "Recibimos tu solicitud. El acceso al ticket se guardó en este dispositivo.", ticket: "Ticket", status: "Estado", check: "Actualizar estado", note: "Nota de soporte", categories: { TECHNICAL: "Problema técnico", CONTENT_CORRECTION: "Corrección del Corán/traducción", PRIVACY: "Privacidad", ACCOUNT_DELETION: "Eliminar cuenta", SECURITY: "Seguridad", OTHER: "Otro" } },
  ar: { home: "الرئيسية", title: "الدعم", intro: "أرسل طلبات الدعم الفني أو تصحيح المحتوى أو الخصوصية أو الأمان أو حذف الحساب مباشرة إلى فريقنا.", email: "البريد الإلكتروني (اختياري)", emailHint: "أضفه إذا رغبت في أن نتمكن من التواصل معك.", category: "الموضوع", message: "التفاصيل", placeholder: "اذكر نوع الجهاز وإصدار التطبيق والمشكلة. لا تكتب كلمة المرور أو بيانات حساسة.", send: "إرسال الطلب", sending: "جارٍ الإرسال…", success: "تم استلام طلبك وحُفظ الوصول إلى التذكرة على هذا الجهاز.", ticket: "التذكرة", status: "الحالة", check: "تحديث الحالة", note: "ملاحظة الدعم", categories: { TECHNICAL: "مشكلة تقنية", CONTENT_CORRECTION: "تصحيح آية/ترجمة", PRIVACY: "الخصوصية", ACCOUNT_DELETION: "حذف الحساب", SECURITY: "الأمان", OTHER: "أخرى" } },
};
type Ticket = { id: string; accessToken: string; status: string; adminNote?: string | null };

export function SupportDocument() {
  const params = useSearchParams(); const requested = params.get("lang") as Language | null; const lang: Language = requested && requested in copy ? requested : "tr"; const t = copy[lang];
  const [email, setEmail] = useState(""); const [category, setCategory] = useState("TECHNICAL"); const [message, setMessage] = useState(""); const [ticket, setTicket] = useState<Ticket | null>(null); const [busy, setBusy] = useState(false); const [error, setError] = useState<string | null>(null);
  useEffect(() => { try { const saved = localStorage.getItem("support_ticket"); if (saved) queueMicrotask(() => setTicket(JSON.parse(saved))); } catch {} }, []);
  const submit = async (event: FormEvent) => { event.preventDefault(); setBusy(true); setError(null); try { const response = await apiClient.post<Ticket>("/support", { email, category, message, locale: lang }); setTicket(response.data); localStorage.setItem("support_ticket", JSON.stringify(response.data)); setMessage(""); } catch { setError("Request could not be submitted. Please try again."); } finally { setBusy(false); } };
  const refresh = async () => { if (!ticket) return; setBusy(true); try { const response = await apiClient.get<Omit<Ticket, "id" | "accessToken">>(`/support/${ticket.id}?token=${encodeURIComponent(ticket.accessToken)}`); const next = { ...ticket, ...response.data }; setTicket(next); localStorage.setItem("support_ticket", JSON.stringify(next)); } catch { setError("Ticket status could not be loaded."); } finally { setBusy(false); } };
  return <main dir={lang === "ar" ? "rtl" : "ltr"} className="mx-auto min-h-screen max-w-2xl px-5 py-12 text-text"><Link href="/" className="text-sm font-semibold text-primary">← {t.home}</Link><h1 className="mt-8 text-3xl font-bold">{t.title}</h1><p className="mt-3 leading-7 text-secondary">{t.intro}</p>
    {ticket && <section className="mt-7 rounded-lg border border-primary/30 bg-primary/5 p-4"><p className="font-bold text-text">{t.success}</p><p className="mt-2 break-all text-xs text-muted">{t.ticket}: {ticket.id}</p><p className="mt-2 text-sm text-secondary">{t.status}: <b>{ticket.status}</b></p>{ticket.adminNote && <p className="mt-2 text-sm text-secondary">{t.note}: {ticket.adminNote}</p>}<button onClick={() => void refresh()} disabled={busy} className="mt-3 rounded-md border border-primary px-3 py-2 text-sm font-bold text-primary">{t.check}</button></section>}
    <form onSubmit={submit} className="mt-7 space-y-4"><div><label className="text-sm font-bold">{t.email}</label><input type="email" maxLength={254} value={email} onChange={(event) => setEmail(event.target.value)} className="mt-1 w-full rounded-md border border-border bg-card px-3 py-3"/><p className="mt-1 text-xs text-muted">{t.emailHint}</p></div><div><label className="text-sm font-bold">{t.category}</label><select value={category} onChange={(event) => setCategory(event.target.value)} className="mt-1 w-full rounded-md border border-border bg-card px-3 py-3">{categories.map((value) => <option key={value} value={value}>{t.categories[value]}</option>)}</select></div><div><label className="text-sm font-bold">{t.message}</label><textarea required minLength={20} maxLength={3000} value={message} onChange={(event) => setMessage(event.target.value)} placeholder={t.placeholder} className="mt-1 min-h-40 w-full rounded-md border border-border bg-card px-3 py-3"/></div><button disabled={busy} className="rounded-md bg-primary px-5 py-3 font-bold text-white disabled:opacity-60">{busy ? t.sending : t.send}</button>{error && <p className="text-sm font-bold text-red-600">{error}</p>}</form>
    <div className="mt-10 flex flex-wrap gap-2">{(["tr", "en", "ar", "de", "fr", "es"] as Language[]).map((value) => <Link key={value} href={`/support?lang=${value}`} className={`rounded border px-2 py-1 text-xs ${lang === value ? "border-primary text-primary" : "border-border text-muted"}`}>{value.toUpperCase()}</Link>)}</div>
  </main>;
}
